---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: main-page
  labels:
    app: main-page
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: main-page
    type: pod
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
      name: main-page

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-page
  labels:
    app: main-page
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-page
      type: pod
  template:
    metadata:
      labels:
        app: main-page
        type: pod
    spec:
      containers:
        - name: main-page
          image: syamsuldocker/main-page:0.0.0
          ports:
          - containerPort: 80
          