---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: websocket
  labels:
    app: websocket
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: websocket
    type: pod
  ports:
    - protocol: TCP
      port: 12000 # service port
      targetPort: 12000 # container port
      name: websocket

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-deployment
  labels:
    app: websocket
    type: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket
      type: pod
  template:
    metadata:
      labels:
        app: websocket
        type: pod
    spec:
      containers:
      - name: websocket
        image: 717420436752.dkr.ecr.ap-southeast-1.amazonaws.com/websocket:cabf0e8-18
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 12000
        envFrom:
          - configMapRef:
              name: websocket-env
        command: ["node", "dist/main.js"]

