apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "syamsul.online"
      - "jaeger.syamsul.online"
      - "prometheus.syamsul.online"
      - "url.syamsul.online"
      - "grafana.syamsul.online"
      - "kiali.syamsul.online"
      - "user.syamsul.online"

---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: app-vs
spec:
  hosts:
    - "syamsul.online"
    - "jaeger.syamsul.online"
    - "prometheus.syamsul.online"
    - "url.syamsul.online"
    - "grafana.syamsul.online"
    - "kiali.syamsul.online"
    - "user.syamsul.online"
  gateways:
  - app-gateway
  http:
  - match:
    - uri:
        prefix: /
      headers:
        host:
          exact: "url.syamsul.online"
    route:
    - destination:
        host: url-shortener
        port:
          number: 10000
  - match:
    - uri:
        prefix: /
      headers:
        host:
          exact: "jaeger.syamsul.online"
    route:
    - destination:
        host: jaeger.obs.svc.cluster.local
        port:
          number: 16686
  - match:
    - uri:
        prefix: /
      headers:
        host:
          exact: "prometheus.syamsul.online"
    route:
    - destination:
        host: prometheus.obs.svc.cluster.local
        port:
          number: 9090
  - match:
    - uri:
        prefix: /
      headers:
        host:
          exact: "grafana.syamsul.online"
    route:
    - destination:
        host: grafana.obs.svc.cluster.local
        port:
          number: 3000
  - match:
    - uri:
        prefix: /
      headers:
        host:
          exact: "kiali.syamsul.online"
    route:
    - destination:
        host: kiali.obs.svc.cluster.local
        port:
          number: 20001
  - match:
    - uri:
        prefix: /
      headers:
        host:
          exact: "user.syamsul.online"
    route:
    - destination:
        host: user
        port:
          number: 10000


# curl -v -H "Host: url.syamsul.online" http://a8bf107b1662b41fe8b69a4363827310-1058936761.ap-southeast-1.elb.amazonaws.com