---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: user
    type: pod
  ports:
    - protocol: TCP
      port: 10000 # service port
      targetPort: 10000 # container port
      name: user

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      type: pod
  template:
    metadata:
      labels:
        app: user
        type: pod
    spec:
      containers:
      - name: user
        image: 717420436752.dkr.ecr.ap-southeast-1.amazonaws.com/user:cabf0e8-18
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10000
        envFrom:
          - configMapRef:
              name: user-env
        command: ["./main"]

