services:
    
  main-page:
    container_name: main-page
    hostname: main-page
    image: main-page
    ports:
      - "8003:80" # can be closed for security
    networks:
      - my-network
    # working_dir: /app
    # volumes:
    #   - .env:/app/.env
    #   - ./main:/app/main
    # command: ["./main"]
    # env_file:
    #   - ".env"

  
networks:
  my-network:
    name: my-network
    external: true