---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: url-shortener
  labels:
    app: url-shortener
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: url-shortener
    type: pod
  ports:
    - protocol: TCP
      port: 10000 # service port
      targetPort: 10000 # container port
      name: url-shortener

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
  labels:
    app: url-shortener
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
      type: pod
      version: stable
  template:
    metadata:
      labels:
        app: url-shortener
        type: pod
        version: stable
    spec:
      containers:
      - name: url-shortener
        image: docker.io/library/url-shortener:testing
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10000
        envFrom:
          - configMapRef:
              name: url-shortener-env
        command: ["./main"]


