---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: prometheus
    type: pod
  ports:
    - protocol: TCP
      port: 9090 # service port
      targetPort: 9090 # container port
      name: prometheus

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      type: pod
  template:
    metadata:
      labels:
        app: prometheus
        type: pod
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
          - containerPort: 9090
          command:
            - /bin/prometheus
            - --config.file=/config.yaml
            - --storage.tsdb.retention.time=7d
            - --web.external-url=/prometheus
          volumeMounts:
            - name: prometheus-configmap
              mountPath: /config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: prometheus-configmap
          configMap:
            name: prometheus-configmap

