---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: graph-clusterip
  labels:
    app: graph
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: graph
    type: pod
  ports:
    - protocol: TCP
      port: 10000 # service port
      targetPort: 10000 # container port
      name: graph-clusterip

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-deployment
  labels:
    app: graph
    type: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: graph
      type: pod
  template:
    metadata:
      labels:
        app: graph
        type: pod
    spec:
      containers:
      - name: graph
        image: <ECR>
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10000
        envFrom:
          - configMapRef:
              name: graph-env
        command: ["./main"]

