version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.48
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "9411:9411" # Zipkin compatible collector
    environment:
      JAEGER_COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      JAEGER_COLLECTOR_ZIPKIN_ENABLED: "true"
    networks:
      - test
    command: ["--collector.zipkin.host-port=9411"] # explicitly enable Zipkin collector

networks:
  test:
    external: true
